schema_version = "1.0.0"

id = "ninja_gaiden_tmc"
version = "3.1.0"
name = "Ninja Gaiden Sigma 1 and 2 TMC Format"
tagline = "Import Ninja Gaiden Sigma 1 and 2 TMC"
maintainer = "Nozomi Miyamori"
type = "add-on"

blender_version_min = "4.2.0"

license = [
    "SPDX:CC0-1.0",
]

[permissions]
files = "Import TMC from disk"
